apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: service-f
spec:
  releaseName: service-f
  chart:
    spec:
      chart: service-f
      sourceRef:
        kind: HelmRepository
        name: service-f
        namespace: flux-system
      version: "1.0.0"
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  values:
    image:
      repository: xxxxxxxxxxxx.dkr.ecr.ap-southeast-1.amazonaws.com/99co-service-f-prd:<commit_hash>